// Icônes Lucide uniquement (trait de 2 px, couleur du texte). Les entrées de menu
// désignent une icône par son nom ; seules celles listées ici sont embarquées.
import type { Component } from 'vue'
import {
  Download,
  Heart,
  House,
  Map as CarteIcone,
  MessageSquare,
  User,
  Users,
  X,
  Check,
  Info,
  TriangleAlert,
  Search,
  MapPin,
  ShieldCheck,
  Menu as MenuIcone,
  LogOut,
  KeyRound,
  UserCog,
  ClipboardList,
  Bell,
  Settings,
  BadgeCheck,
  IdCard,
  Camera,
  LayoutDashboard,
  FileText,
  Eye,
  Activity,
  Bug,
  History,
  Flag,
  Megaphone,
} from 'lucide-vue-next'

export const icones: Record<string, Component> = {
  accueil: House,
  carte: CarteIcone,
  favoris: Heart,
  messages: MessageSquare,
  profil: User,
  groupes: Users,
  telecharger: Download,
  fermer: X,
  valide: Check,
  info: Info,
  attention: TriangleAlert,
  recherche: Search,
  position: MapPin,
  admin: ShieldCheck,
  menu: MenuIcone,
  deconnexion: LogOut,
  securite: KeyRound,
  utilisateurs: Users,
  administrateurs: UserCog,
  file: ClipboardList,
  relance: Bell,
  parametres: Settings,
  identite: IdCard,
  badge: BadgeCheck,
  camera: Camera,
  tableau: LayoutDashboard,
  annonce: FileText,
  visites: Eye,
  supervision: Activity,
  erreur: Bug,
  historique: History,
  signalement: Flag,
  communique: Megaphone,
}

export type NomIcone = keyof typeof icones
